runtime: python311  # or your Python version
entrypoint: gunicorn receipt_reader.wsgi

instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "receipt_reader.settings"
  SECRET_KEY: "django-insecure-h$_tff3x8=&k49qml6+2dr^nry(recppo&jr10sd4w!f^mm=j@"
  ALLOWED_HOSTS: ".appspot.com"

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto
